"""
Confidence Scorer
-----------------
Assigns a trust score (0.0–1.0) to every field extracted from every source.

Design philosophy:
  - Structured sources (CSV, ATS) get higher baseline confidence than
    unstructured ones (GitHub bio, scraped pages).
  - LLM-extracted data from resumes gets its own tier ("resume_llm") —
    high confidence because the model has full document context.
  - Certain fields are inherently more reliable from certain sources
    (e.g., GitHub is the authoritative source for github_url, but a
    recruiter CSV is more reliable for phone numbers).
  - When multiple sources agree on a value, we can *boost* confidence —
    this is handled by the merger, not here.
  - Semantic similarity between two string field values from different
    sources can be used to apply a soft-agreement boost.
"""

from typing import Dict, Optional, List


# ---------------------------------------------------------------------------
# Per-source, per-field confidence matrix
# ---------------------------------------------------------------------------
# Each source has a dict mapping field_name -> confidence.
# A "default" key catches any field not explicitly listed.
# A "_source_tier" key captures the baseline trust for the source category.

_CONFIDENCE_MATRIX: Dict[str, Dict[str, float]] = {
    "recruiter_csv": {
        "_source_tier": 0.85,       # Structured, manually entered data
        "name":            0.90,
        "email":           0.90,
        "phone":           0.90,
        "current_company": 0.80,
        "title":           0.80,
        "location":        0.70,
        "skills":          0.75,    # Recruiter-reported skills (may be approximate)
        "linkedin":        0.85,    # Direct URL, usually accurate
        "years_experience":0.75,    # Recruiter estimate, reasonable
        "education":       0.80,    # Usually verified by recruiters
        "degree":          0.80,
        "default":         0.60,
    },
    "github_api": {
        "_source_tier": 0.70,       # Unstructured, self-reported
        "name":            0.70,
        "login":           1.00,    # Authoritative — it IS the username
        "email":           0.60,    # Often null or personal throwaway
        "bio":             0.75,
        "location":        0.65,    # Self-reported free text
        "github_url":      1.00,    # Authoritative link
        "blog":            0.80,
        "public_repos":    1.00,    # Factual count from the API
        "languages":       0.85,    # Derived from actual repo code
        "default":         0.55,
    },
    # ── New: LLM-extracted from resume text ───────────────────────────────
    "resume_llm": {
        "_source_tier": 0.88,       # High trust: model has full document context
        "full_name":       0.88,
        "email":           0.85,
        "phone":           0.80,    # LLM may misread phone formatting
        "headline":        0.85,
        "skills":          0.87,    # LLM is great at skill extraction
        "experience":      0.87,    # Structured extraction from full context
        "education":       0.86,
        "years_experience":0.82,    # Computed from date ranges
        "location":        0.80,
        "links":           0.82,
        "llm_summary":     0.90,    # Generated by the model — always present
        "default":         0.75,
    },
    # ── New: Heuristic-parsed from resume (before LLM enrichment) ─────────
    "resume_parsed": {
        "_source_tier": 0.72,       # Regex/heuristic — less reliable
        "name":            0.70,    # Name heuristic is imperfect
        "email":           0.88,    # Regex email is very reliable
        "phone":           0.78,    # Regex phone can match false positives
        "github_url":      0.88,    # URL regex is reliable
        "linkedin":        0.88,
        "default":         0.55,
    },
}


# ---------------------------------------------------------------------------
# Field importance weights (used for overall_confidence calculation)
# ---------------------------------------------------------------------------
# Higher weight = this field matters more when computing the aggregate score.
# Fields not listed here default to 1.0.

FIELD_IMPORTANCE: Dict[str, float] = {
    "full_name":    2.0,
    "emails":       1.8,
    "phones":       1.5,
    "headline":     1.2,
    "skills":       1.5,
    "location":     1.0,
    "links":        0.8,
    "experience":   1.3,
    "education":    1.0,
    "llm_summary":  0.5,   # supplementary — not a core identity field
}

# Semantic similarity threshold for soft-agreement boost
_SEMANTIC_AGREEMENT_THRESHOLD = 0.85
_SEMANTIC_BOOST               = 0.05


def get_confidence_score(source_name: str, field_name: str) -> float:
    """
    Returns a confidence score between 0.0 and 1.0 for a given field
    extracted from a specific source.

    Parameters
    ----------
    source_name : str
        The identifier of the data source (e.g. "recruiter_csv", "resume_llm").
    field_name : str
        The raw field name as it appears in the extracted data.

    Returns
    -------
    float
        Confidence score in range [0.0, 1.0].
    """
    source_scores = _CONFIDENCE_MATRIX.get(source_name, {})
    return source_scores.get(field_name, source_scores.get("default", 0.5))


def get_source_tier(source_name: str) -> float:
    """
    Returns the baseline trust tier for an entire source category.
    Useful for tie-breaking when two sources report the same field
    with identical per-field scores.
    """
    source_scores = _CONFIDENCE_MATRIX.get(source_name, {})
    return source_scores.get("_source_tier", 0.5)


def compute_multi_source_boost(base_confidence: float, agreeing_sources: int) -> float:
    """
    When N sources agree on a value, we boost the confidence.

    Formula: min(1.0, base + 0.05 * (N - 1))
    - Two sources agreeing adds +0.05
    - Three adds +0.10
    - Capped at 1.0

    Parameters
    ----------
    base_confidence : float
        The original confidence from the winning source.
    agreeing_sources : int
        Total number of sources that reported the same (or equivalent) value.

    Returns
    -------
    float
        Boosted confidence, capped at 1.0.
    """
    if agreeing_sources <= 1:
        return base_confidence
    boost = 0.05 * (agreeing_sources - 1)
    return min(1.0, round(base_confidence + boost, 4))


def compute_semantic_similarity_boost(
    embedding_a: List[float],
    embedding_b: List[float],
    base_confidence: float,
    threshold: float = _SEMANTIC_AGREEMENT_THRESHOLD,
    boost: float = _SEMANTIC_BOOST,
) -> float:
    """
    Apply a soft-agreement boost when two embedded field values are
    semantically similar (e.g. "Software Engineer" ≈ "SWE").

    Requires pre-computed embeddings from the RAG embedder.

    Parameters
    ----------
    embedding_a, embedding_b : list[float]
        Dense vectors for the two field values being compared.
    base_confidence : float
        Current confidence of the winning value.
    threshold : float
        Cosine similarity threshold for soft agreement (default 0.85).
    boost : float
        Confidence boost to apply when similarity >= threshold (default 0.05).

    Returns
    -------
    float
        Possibly-boosted confidence, capped at 1.0.
    """
    try:
        from lc.embedder import cosine_similarity
        sim = cosine_similarity(embedding_a, embedding_b)
        if sim >= threshold:
            return min(1.0, round(base_confidence + boost, 4))
    except Exception:
        pass   # If embedder fails, just return base confidence
    return base_confidence


def compute_overall_confidence(
    field_confidences: Dict[str, float],
    importance_weights: Optional[Dict[str, float]] = None,
) -> float:
    """
    Compute a single overall confidence score for a candidate profile
    using a weighted average of per-field confidences.

    Parameters
    ----------
    field_confidences : dict
        Mapping of field_name -> confidence score for fields that were populated.
    importance_weights : dict, optional
        Mapping of field_name -> weight. Defaults to FIELD_IMPORTANCE.

    Returns
    -------
    float
        Weighted average confidence, rounded to 2 decimal places.
    """
    if not field_confidences:
        return 0.0

    weights = importance_weights or FIELD_IMPORTANCE

    total_weight = 0.0
    weighted_sum = 0.0

    for field, conf in field_confidences.items():
        w = weights.get(field, 1.0)
        weighted_sum += conf * w
        total_weight += w

    if total_weight == 0:
        return 0.0

    return round(weighted_sum / total_weight, 2)
